pgwatch:
  extraVolumes:
    - name: pgwatch-crunchy-sources
      configMap:
        name: pgwatch-crunchy-sources-cm
        optional: true

  extraVolumeMounts:
    - name: pgwatch-crunchy-sources
      mountPath: /tmp/pgwatch-sources/sources-dynamic.yaml
      subPath: sources-dynamic.yaml

  service:
    ports:
      - name: http
        port: 8080
        targetPort: 8080
      - name: metrics
        port: 9188
        targetPort: 9188

  postgres:
    enablePgSink: false
    credentials:
      username: "pgwatch"
      password: "dummyPassword123!"
    adminCredentials:
      password: "dummyAdminPassword123!"
  prometheus:
    enablePromSink: true
    newPrometheus:
      createPrometheus: false
  grafana:
    enableGrafana: false
  podAnnotations:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: "pgwatch-sources-secret"

  # The chart will mount this block directly into /tmp/pgwatch-sources/sources.yaml
  sources:
    files:
      sources.yaml: |
        - name: POSTGRES_ALPHA_CONN
          conn_str: ${POSTGRES_ALPHA_CONN}
          preset_metrics: full
          is_enabled: true
          custom_tags:
            customer: ALPHA_CONN
            role: primary
            region: us-east-1

        - name: POSTGRES_BETA_CONN
          conn_str: ${POSTGRES_BETA_CONN}
          preset_metrics: full
          is_enabled: true
          custom_tags:
            customer: BETA_CONN
            role: primary
            region: us-west-1

  # Inject the secret keys as environment variables into the pod
  envFrom:
    - secretRef:
        name: pgwatch-sources-secret
