apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pgwatch
  namespace: pgwatch
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - pgwatch
  selector:
    matchLabels:
      app.kubernetes.io/name: pgwatch
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
