apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pgwatch
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - pgwatch
  selector:
    matchLabels:
      app.kubernetes.io/component: pgwatch
      app.kubernetes.io/name: pgwatch
  endpoints:
    - port: prometheus
      interval: 15s
      path: /metrics


