---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgwatch-sources-secret
  namespace: pgwatch
spec:
  encryptedData:
    POSTGRES_ALPHA_CONN: AgBJEa+gyrfR+Ts10hMNFYEQgqN+3dRBD+S1Fh+4Ya2tntOnTpXIgNdvZkpA5uchxiKw6SkgzfJ2z/L6D46iGpwRaIxlcWXy1xI/8//ttvGejFVLmQgK+/8GDes1KSK5Oqut7Wvqac2xo8zpGGuKaNsQWsbG4M5UjI1tKNc1Z4GMoj7NrC0KCE79SYGeVoJO9vJe66k/jsjEfiD3dcg6MX3JkpNikoZ/1Qt5xo5YaQBSb1ap4Uaw6obBpWo52YTeFRM5HvtmR38fQ+7Kdd/Ac/XKCi/EP3llbwAh6cHkzEcK4H7YCZH05wi2nQq3qlZLEfYGEm1I0ijMc6SWUqEL68k9UOPne8/rkRVl7rN4Rmq7gC6uqk1aDwhNa+oMKBsZMiQu5YgTu1sSp0vYUqfQCw4mQiE/nC/nqSH7c0GkPrezoVvMhoK2EqrfEsaUusEXEXExCGYugRr64o0SYqpNhjOr+nsEUL1IZXnFh0+nWFz1cp+G+lJ+tWTookR/uKVDgAxmHVkkx2FOHpIqMFrrzsPyGSMCj4MD32e7Gtf42K7LbP/SyABIVDQfKfcApa4byzCh7NjOk86iKoh83WKGpQMeWawR47jD28urovh5noZ7lm80hjA3zfEoGB4iLyfUcSXZesttUDu9CHlqTcK4iawcK1s29/nbQj5RiJ8pwqhlwdNjbpHULFzYfN9YWtqlkEyx57mzVWm+nyogzvAkaF15ApmcJ0q7SRAn85CDZfM4fvdcdI6sNkREMM52ulAAQ9Bvq+bfCYohE5VRzIIfzAC57g==
  template:
    metadata:
      name: pgwatch-sources-secret
      namespace: pgwatch
