---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgwatch-sources-secret
  namespace: pgwatch
spec:
  encryptedData:
    sources.yaml: AgAjejOxENvWCHVAyK8fgAq8MABuP/Pl++oU8H1cP8aYLGLgpo0mv2HSaW39qEHJl4NeNVePzv/llys16lDHOYDUemldUpFQIimvOpDEXhqyTLZWHR7PY3y08zzHCiWQP6j2HtaTXIwN+vzSkBlm6kuKc0ztesfrDh8UybnclyebRPjLiXNaNVzqEe8ejJmmwihT77cDWiGz0H7H7OwEnkOvEkUcnnGzB65HK/bdAC/MobiZ3eWMUH0PCdIhYeqfLhOJDjvqeEUKQ8MvgMsabp+uSGX3FKes7dQiCUS/wWs+r/kHR4fJDkxfwAI3Y2P7dFZrAONDUcPtuXA1YlNIMcw73AOxtFLciODZZn6aM/MoVuG87Jiq+Re3es21z6q1ytiXh4QpSCl0axskTzVKLtOX9QJ6dsxuqJ8RCKoz/nuwe4y6OX8Ds4vkTz009NyWlkc/b/jFK0HTQ11yOkt4OPFwKZOEwxMMol3OccZB+8N8650bYH/AdniNJGVWWwLJTut+7IZbNTiHjkvTahG6j/h0VPmUYVEhgu8wowQCFXu2y2PWD9MR+Dzt7nqWlTgqvEqLEFJqN/QjgxYmOXy7R4oWzYYynOkDR6Id9KkCrsayeloUNbF5R9c2Qq3m/8c4C5PjWc9PuwRNzNMOXSB7udza/VSr+aYirvBec+d49INXs56UsYNNpaPIpNSpzkXzW1Izgc/8NxqAU1a5d7M53zxJr9of92IW5NREYt3FFU5tAyu0JQHwzPeK4zIlGA0VqU56pKgJJ0mqolSkAXGWINMlbgveNjuD3N8RX+DqUDSj36vEShNFVQ2lCo6s9v+tML9ciVYiHV8DtlnaQB67Zy6IznZrd7F1YPPfGdr8d2YmBRfO9vmyfZcjz74B0la55J0SlNDrT5SoWGWrh/AKmdSBkIZu6oChgaR9vQxkFPahkkkQMy5FA+YcaDevA1yrWh6ycuFEH7GjRTSHhjz6kievtW0/bOWoc2/7VNYKSLTKbLqd4ogMz8m0tUlyEoNOSlfiNLDAG67ePkWNwOQjtNRCxl8KzYTygn7qAapymwYkLn2555Samd71wBTSteanDmGQhGzvAl8g+g==
  template:
    metadata:
      name: pgwatch-sources-secret
      namespace: pgwatch
