apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: pgwatch-crunchy-db06t-dev
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  scheme: HTTPS
  scrapeInterval: 30s
  scrapeTimeout: 15s
  tlsConfig:
    insecureSkipVerify: true
  staticConfigs:
    - targets:
        - "pgwatch-metrics-dev.apps.db06t.sbb-aws-test.net:443"
      labels:
        environment: dev
        cluster: db06t
        job: pgwatch-crunchy-exporter
