apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -customer-alpha  # Creates 'pgwatch-base-alerts-customer-alpha'

patches:
  - target:
      kind: PrometheusRule
      name: pgwatch-base-alerts
      namespace: monitoring
    path: patch-disk.yaml
