apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pgwatch-customer-overlays
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/WellingtoneLuvonga/pgwatch-gitops-wellingtone.git
        revision: HEAD
        directories:
          - path: overlays/*/*
  template:
    metadata:
      name: 'pgwatch-{{path[1]}}-{{path.filename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/WellingtoneLuvonga/pgwatch-gitops-wellingtone.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: pgwatch
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
