apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgwatch-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/WellingtoneLuvonga/pgwatch-gitops-wellingtone.git
    targetRevision: HEAD
    path: .
    directory:
      include: '{sealed-sources.yaml,pgwatch-podmonitor.yaml,pgwatch-discovery-rbac.yaml,pgwatch-crunchy-watcher.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: pgwatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
